#if defined _bb_entity_consts_included
    #endinput
#endif
#define _bb_entity_consts_included

stock const BB_OBJECT[] = "bb_object";
stock const BB_OBJECT_RAW[] = "bb_object_";
stock const BB_ILLUSIONARY[] = "bb_illusionary";
stock const BB_TERRITORY[] = "bb_territory";
stock const BB_TIMER[] = "bb_timer";

stock const BB_BARRIER[][] = { "bb_barrier", "barrier", "Barrier" };
stock const BB_IGNORE[][] = { "bb_ignore", "ignore", "blockers" };
stock const BB_BUILDER_SPAWN[] = "bb_builder_spawn";
stock const BB_ZOMBIE_SPAWN[] = "bb_zombie_spawn";

