#if defined _basebuilder_included
	#endinput
#endif
#define _basebuilder_included

#include "include/bb/bb_core.inc"
//#include "include/bb/bb_credits.inc"
#include "include/bb/bb_commands.inc"
#include "include/bb/bb_zombies.inc"
#include "include/bb/bb_classes.inc"
#include "include/bb/bb_game.inc"
#include "include/bb/bb_colorchat.inc"
#include "include/bb/bb_builder.inc"
#include "include/bb/bb_colors.inc"