#if defined _bb_cr_const_included
	#endinput
#endif
#define _bb_cr_const_included

/******************************************************************************************************************************
Data/Definitions
******************************************************************************************************************************/

/**
 * Defined value for the version of this plugin.
 */
#define BB_CR_VERSION 0.0.1

/**
 * String representation for the name of this plugin.
 */
stock const BB_CR_PLUGIN_NAME[] = "Base Builder [Credits]";

/**
 * String representation for the version of this plugin. (Should match BB_VERSION)
 */
stock const BB_CR_PLUGIN_VERSION[] = "0.0.1";

/**
 * String representation for the name of the file which stores the game key.
 */
stock const BB_GAME_KEY_FILE[] = "bb_gamekey.txt";