#if defined _bb_playermodels_const_included
	#endinput
#endif
#define _bb_playermodels_const_included

/******************************************************************************************************************************
Data/Definitions
******************************************************************************************************************************/

/**
 * Representation for the tag of a BB_MODEL
 */
#define BB_MODEL: any: